//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace squadHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_squadHealth
    {
        public int Id { get; set; }
        public int sprintId { get; set; }
        public System.DateTime lastUpdateTime { get; set; }
        public int questionNumber { get; set; }
        public string colour { get; set; }
        public string userId { get; set; }
    }
}
